### ISSUE TITLE
Issue with qtlpoly::plot_profile

### ISSUE THREAD

**Issue by peterbourke** [guilherme-pereira/QTLpoly#2]
Hi Gui,
I have been going through some of the steps in the vignette, and skipped to the end for the FEIM out of interest. Running the following line:
`plot_profile(data = data, model = feim.mod, grid = TRUE)`
gave the following warning:
_Warning messages:
1: `expand_scale()` is deprecated; use `expansion()` instead. 
2: `expand_scale()` is deprecated; use `expansion()` instead._ 

No plots were produced. I have version 3.3.2 of ggplot2, which is where this comes from. If you use `CRAN = TRUE` in your package check before building, these sorts of issues are often caught. 

BTW, although a separate issue might as well tell you here: in the initial steps for package installation there was an issue with package `SPA3G` (a dependency of `varComp` I think), which is now an archived package. I downloaded the archived tarball from CRAN and installed it myself separately:

`install.packages("SPA3G_1.0.tar.gz",type = "source", repos = NULL)`

Following this, the installation call for `varComp` worked OK. 

Best regards,
Peter

**Comment by guilherme-pereira** [comment]
Hi Peter,

Thanks for pointing these issues out. 

I've updated the [instructions](https://github.com/guilherme-pereira/QTLpoly#install-qtlpoly-package) for `SPA3G` installation as well as the ggplot2 deprecated function. 

Best regards,

Gui.

**Comment by peterbourke** [comment]
Thanks Gui, that has fixed it.

Continuing the same thread, when I run the `remim` function of the vignette and then subsequently try to plot the results using
`plot_profile(data = data, model = remim.mod, grid = TRUE)`

I get the following error:

`Error in seq.default(0, max(lines$SIG), cuty) : 
  'to' must be a finite number`

I see the plot in the vignette on GitHub already, but just to let you know something weird is still going on.

Best,
Peter

**Comment by guilherme-pereira** [comment]
Hi Peter,

It's been fixed now. Thank you for letting me know. 

Gui.
